# **1. Perkenalan Dataset**

Dataset yang digunakan merupakan data sosial ekonomi warga di Kecamatan Mlati, Kabupaten Sleman tahun 2023. Dataset ini diperoleh dari SIMNANGKIS (Sistem Informasi Manajemen Penanggulangan Kemiskinan) Dinas Sosial Kabupaten Sleman.

Dataset memiliki 33.842 baris dan 59 atribut, yang mencakup:

1. Data demografi (usia, jenis kelamin, status perkawinan)
2. Kondisi hunian (lantai, dinding, atap, sumber air, listrik)
3. Kepemilikan aset (motor, mobil, TV, kulkas, dll)
4. Kondisi sosial ekonomi (pendidikan, pekerjaan, usaha)

Dataset ini digunakan untuk:
> classification task → memprediksi tingkat kesejahteraan warga (rendah, sedang, tinggi) berdasarkan kondisi sosial ekonomi.

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.

In [1]:
# manipulasi data
import pandas as pd
import numpy as np
import os
import shutil

# visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

In [2]:
import kagglehub

path = kagglehub.dataset_download("azizp123/simnangkis-eksport-mlati")
print("Path dataset:", path)

C:\Users\PERSONAL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path dataset: C:\Users\PERSONAL\.cache\kagglehub\datasets\azizp123\simnangkis-eksport-mlati\versions\11

In [3]:
os.listdir(path)

['simnangkis_eksport_mlati.csv', 'simnangkis_eksport_mlati_preprocessed.csv']

In [4]:
shutil.copy(
    os.path.join(path, "simnangkis_eksport_mlati.csv"),
    "../simnangkis_eksport_mlati_raw/simnangkis_eksport_mlati.csv"
)

'../simnangkis_eksport_mlati_raw/simnangkis_eksport_mlati.csv'

In [5]:
df = pd.read_csv(os.path.join(path, "simnangkis_eksport_mlati.csv"))
df.head()

,status,id_kelamin,kelurahan,dusun,id_hub_rumah_tangga,id_hub_keluarga,usia,id_nikah,id_difable,id_penyakit_kronis,...,ada_kapal,aset_tak_bergerak,luas_atb,rumah_lain,jumlah_sapi,jumlah_kerbau,jumlah_kuda,jumlah_babi,jumlah_kambing,sta_art_usaha
0,miskin,2.0,Sendangadi,12.0,3.0,3.0,20.0,1.0,0.0,0.0,...,2.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0
1,miskin,2.0,Sendangadi,12.0,3.0,3.0,22.0,1.0,0.0,0.0,...,2.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0
2,miskin,2.0,Sendangadi,12.0,1.0,1.0,41.0,3.0,0.0,0.0,...,2.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0
3,miskin,1.0,Sendangadi,14.0,3.0,3.0,40.0,1.0,0.0,0.0,...,2.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0
4,miskin,2.0,Sendangadi,14.0,2.0,2.0,67.0,2.0,0.0,0.0,...,2.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0

# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.

## **1. Cek Missing Values**

In [6]:
df.isnull().sum().sort_values(ascending=False)

jumlah_kuda                  23958
jumlah_babi                  23955
jumlah_kerbau                23949
id_keberadaan                23660
jumlah_sapi                  23258
jumlah_kambing               23094
nama_sls                     22809
dusun                        22203
id_status_dalam_pekerjaan    20545
id_pekerjaan                 20115
id_pendidikan                13597
id_ijazah                    11360
luas_atb                     10365
sta_art_usaha                 6195
id_partisipasi_sekolah        6188
kondisi_dinding               5360
jumlah_kamar                  5230
daya                          5172
sta_lahan                     5049
kloset                        5015
kondisi_atap                  5010
luas_lantai                   4944
atap                          4931
buang_tinja                   4931
cara_peroleh_air_minum        4931
lantai                        4931
dinding                       4930
fas_bab                       4930
sumber_air_minum              4930
sta_bangunan                  4930
sumber_penerangan             4930
bb_masak                      4930
aset_tak_bergerak             4712
rumah_lain                    4711
ada_emas                      4704
ada_laptop                    4704
ada_kapal                     4704
ada_tv                        4704
ada_telepon                   4704
ada_pemanas                   4704
ada_ac                        4704
ada_lemari_es                 4704
ada_tabung_gas                4704
ada_motor                     4704
ada_mobil                     4704
ada_motor_tempel              4704
ada_perahu_motor              4704
ada_sepeda                    4704
ada_perahu                    4704
usia                          4102
id_kelamin                    3997
id_nikah                      3997
id_hub_keluarga                 84
id_hub_rumah_tangga             84
id_difable                      15
id_penyakit_kronis              15
jml_anggota_keluarga             0
kelurahan                        0
status                           0
dtype: int64

## **2. Statistik Descriptif**

In [7]:
df.describe()

,id_kelamin,dusun,id_hub_rumah_tangga,id_hub_keluarga,usia,id_nikah,id_difable,id_penyakit_kronis,id_partisipasi_sekolah,id_pendidikan,...,ada_kapal,aset_tak_bergerak,luas_atb,rumah_lain,jumlah_sapi,jumlah_kerbau,jumlah_kuda,jumlah_babi,jumlah_kambing,sta_art_usaha
count,29845.000000,11639.000000,33758.000000,33758.000000,29740.000000,29845.000000,33827.000000,33827.000000,27654.000000,20245.000000,...,29138.0000,29130.00000,23477.000000,29131.000000,10584.000000,9893.000000,9884.000000,9887.000000,10748.000000,27647.000000
mean,1.501860,7.741215,2.088631,2.090260,37.476732,1.684269,0.079995,0.092264,1.677334,4.283626,...,2.0000,1.46598,194.404694,3.982562,0.123488,0.003740,0.003136,0.003237,0.364068,1.756357
std,0.500005,4.396062,1.074978,1.075655,46.254868,0.766191,0.852505,0.756631,0.530891,2.808284,...,0.0287,0.49885,1055.028890,0.131424,0.458378,0.083435,0.092687,0.111041,1.373641,0.429288
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,...,1.0000,1.00000,-1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,4.000000,1.000000,1.000000,18.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,2.0000,1.00000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,2.000000,8.000000,2.000000,2.000000,37.000000,2.000000,0.000000,0.000000,2.000000,4.000000,...,2.0000,1.00000,80.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,2.000000,11.000000,3.000000,3.000000,52.000000,2.000000,0.000000,0.000000,2.000000,7.000000,...,2.0000,2.00000,162.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
max,2.000000,18.000000,8.000000,8.000000,2019.000000,4.000000,12.000000,9.000000,2.000000,10.000000,...,4.0000,2.00000,53700.000000,4.000000,4.000000,2.000000,4.000000,6.000000,20.000000,2.000000

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.

## **1. Menghapus atau Menangani Data Kosong (Missing Values)**

In [8]:
# numerik
num_cols = df.select_dtypes(include=np.number).columns
df.loc[:, num_cols] = df[num_cols].fillna(df[num_cols].median())

# kategorikal
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df.loc[:, col] = df[col].fillna(df[col].mode()[0])

## **2. Menghapus Data Duplikat**

In [17]:
df.drop_duplicates(inplace=True)

print("Shape setelah hapus duplikat:", df.shape)

Shape setelah hapus duplikat: (4531, 14)

## **3. Feature Selection**

In [18]:
selected_features = [
    'id_pendidikan', 'id_pekerjaan',
    'lantai', 'dinding', 'atap',
    'sumber_air_minum', 'sumber_penerangan',
    'ada_motor', 'ada_mobil', 'ada_tv', 'ada_lemari_es', 'ada_emas'
]

df = df[selected_features].copy()

df.head()

,id_pendidikan,id_pekerjaan,lantai,dinding,atap,sumber_air_minum,sumber_penerangan,ada_motor,ada_mobil,ada_tv,ada_lemari_es,ada_emas
0,4.0,13.0,4.0,1.0,4.0,6.0,1.0,3.0,2.0,3.0,4.0,2.0
2,4.0,21.0,4.0,1.0,4.0,6.0,1.0,3.0,2.0,3.0,4.0,2.0
3,4.0,21.0,1.0,2.0,2.0,3.0,1.0,4.0,2.0,3.0,4.0,2.0
6,4.0,13.0,6.0,1.0,4.0,5.0,1.0,3.0,2.0,3.0,4.0,2.0
7,4.0,18.0,6.0,1.0,4.0,5.0,1.0,3.0,2.0,3.0,4.0,2.0

## **4. Feature Engineering (Buat Skor)**

In [20]:
df.loc[:, 'skor'] = (
    (df['ada_motor'] == 3).astype(int) +
    (df['ada_mobil'] == 3).astype(int) +
    (df['ada_tv'] == 3).astype(int) +
    (df['ada_lemari_es'] == 3).astype(int) +
    (df['ada_emas'] == 1).astype(int)
)

df.head()

,id_pendidikan,id_pekerjaan,lantai,dinding,atap,sumber_air_minum,sumber_penerangan,ada_motor,ada_mobil,ada_tv,ada_lemari_es,ada_emas,skor
0,4.0,13.0,4.0,1.0,4.0,6.0,1.0,3.0,2.0,3.0,4.0,2.0,2
2,4.0,21.0,4.0,1.0,4.0,6.0,1.0,3.0,2.0,3.0,4.0,2.0,2
3,4.0,21.0,1.0,2.0,2.0,3.0,1.0,4.0,2.0,3.0,4.0,2.0,1
6,4.0,13.0,6.0,1.0,4.0,5.0,1.0,3.0,2.0,3.0,4.0,2.0,2
7,4.0,18.0,6.0,1.0,4.0,5.0,1.0,3.0,2.0,3.0,4.0,2.0,2

## **5. Buat Target Kategori**

In [23]:
def kategori_kesejahteraan(skor):
    if skor <= 2:
        return 'rendah'
    elif skor <= 4:
        return 'sedang'
    else:
        return 'tinggi'

df.loc[:, 'kesejahteraan'] = df['skor'].apply(kategori_kesejahteraan)

## **6. Encoding**

In [25]:
def encode_data(df):
    le = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == 'object':
            df.loc[:, col] = le.fit_transform(df[col])

    return df

## **7. Feature Scaling**

In [26]:
def scaling(df):
    scaler = StandardScaler()
    feature_cols = df.drop(
        'kesejahteraan',
        axis=1
    ).columns

    df.loc[:, feature_cols] = scaler.fit_transform(
        df[feature_cols]
    )

    return df

df.head()

,id_pendidikan,id_pekerjaan,lantai,dinding,atap,sumber_air_minum,sumber_penerangan,ada_motor,ada_mobil,ada_tv,ada_lemari_es,ada_emas,skor,kesejahteraan
0,4.0,13.0,4.0,1.0,4.0,6.0,1.0,3.0,2.0,3.0,4.0,2.0,2,rendah
2,4.0,21.0,4.0,1.0,4.0,6.0,1.0,3.0,2.0,3.0,4.0,2.0,2,rendah
3,4.0,21.0,1.0,2.0,2.0,3.0,1.0,4.0,2.0,3.0,4.0,2.0,1,rendah
6,4.0,13.0,6.0,1.0,4.0,5.0,1.0,3.0,2.0,3.0,4.0,2.0,2,rendah
7,4.0,18.0,6.0,1.0,4.0,5.0,1.0,3.0,2.0,3.0,4.0,2.0,2,rendah

## **8. Split Data**

In [27]:
X = df.drop('kesejahteraan', axis=1)
y = df['kesejahteraan']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42
                                                    )

print("Shape X_train:", X_train.shape)
print("Shape X_test:", X_test.shape)

Shape X_train: (3624, 13)
Shape X_test: (907, 13)